### ISSUE TITLE
Missing support for batch sending

### ISSUE THREAD

**Issue by simplenotezy** [jiangtaste/nestjs-resend#156]
**Is your feature request related to a problem? Please describe.**
https://resend.com/docs/api-reference/emails/send-batch-emails

**Comment by jiangtaste** [comment]
Hi there,

Thank you for your feedback! I'm happy to inform you that support for batch sending has been added in version 1.0.1. You can now send multiple requests in one go, which should enhance your experience.

Please try it out and let me know if you have any further questions or suggestions!

Best regards,
Paul
